install:
	cd backend; cp copy.env .env
	cd frontend; cp copy.env .env
	cd backend; npm i
	cd frontend; npm i

bdev:
	cd backend; npm run start

fdev:
	cd frontend; npm run start

prod:
	cd frontend; npm run build
